image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: ignore
    visibility: public
  - port: 9001
    onOpen: ignore
vscode:
  extensions:
    - felixfbecker.php-debug
tasks:
  - command: composer install --working-dir ./src
  - command: apachectl start
