version: '3'
services:
    web:
        build:
            context: .
            args: 
                GIT_PERSONAL_ACCESS_TOKEN: ${GIT_PERSONAL_ACCESS_TOKEN}
            dockerfile: ./Dockerfile
        image: captain-magenta
        container_name: captain-magenta
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_connect_back=1 idekey=VSCODE remote_autostart=1
        ports:
            - '80:80'
        volumes:
            - './src:/var/www/html'
