# SITE CONFIGURATION
url: https://joejcollins.github.io
baseurl: /captain-magenta # the sub path of your site, e.g. /blog/

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: NBN Records App

timezone: Europe/London