# Configuration for deployment to the Google App Engine
runtime: php73

handlers:
# https://cloud.google.com/appengine/docs/standard/php7/config/appref#handlers_element

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /images
  static_dir: public/images

- url: /public/.*
  script: auto
  redirect_http_response_code: 301

env_variables:
  CI_ENVIRONMENT: "development"
  