name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: captain-magenta
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy ./src --quiet --set-env-vars "GAE_KEY1=VALUE1"
